### ISSUE TITLE
Crash when importing world (1.15.2)

### ISSUE THREAD

**Issue by XxZajoZzO** [jmc2obj/j-mc-2-obj#130]
ERROR: Uncaught exception in thread: ViewChunkLoader
java.lang.ArrayIndexOutOfBoundsException: 256
	at org.jmc.Chunk.getBlocks(Chunk.java:300)
	at org.jmc.Chunk.renderImages(Chunk.java:383)
	at org.jmc.gui.ViewChunkLoaderThread.run(ViewChunkLoaderThread.java:182)
	at java.lang.Thread.run(Unknown Source)

I guess the 1.15.2 is not supported yet

jmc2obj-107

**Comment by mmdanggg2** [comment]
This is happening because the chunk biome format was updated. Biomes can now change across the chunk Y axis. A bit [more information here](https://minecraft.gamepedia.com/Java_Edition_19w36a#General_2):

> Biome information now is stored in sixty-four 4×4 arrays, allowing biomes to be changed based on height; previously, biome values corresponded to only the X and Z coordinates.
The  Biomes array in the  Level tag for each chunk now contains 1024 integers instead of 256. Each number in the array is the biome for a 4x4x4 volume in the chunk. These 4×4×4 volumes are arranged by Z, then X, then Y. That is, the first 4×4 values in the array are for the 16×16 chunk, at Y-levels 0–3, the next 4×4 is for Y-levels 4–7, etc.

**Comment by mmdanggg2** [comment]
This has been fixed in 0e00229cd08b3cd91b29008c388ea5dc81fb874f, update release coming soon.
