### ISSUE TITLE
Dried Kelp filled with water

### ISSUE THREAD

**Issue by Stapelo** [jmc2obj/j-mc-2-obj#131]
I'm not sure if this is the intended behavior  or not, but dried kelp is filled with water. This produces some flickering and other problems when rendering since two surfaces are in the exact same place. 
In the config file the dried kelp looks just like any other block just like it should be.
I cut off one side of a 2x2x2 cube here that illustrates what i mean:
![image](https://user-images.githubusercontent.com/64552495/80632022-ec082a00-8a56-11ea-939c-5260d74677b2.png)

**Comment by Stapelo** [comment]
The same issue seems to happen with the dead coral blocks too.

**Comment by mmdanggg2** [comment]
This is happening because of some fixed rules put in place when they introduced the 'waterlogged' state. The problem is Minecraft isn't storing the waterlogged state for these blocks so there needs to be a more robust way of handling this.
https://github.com/jmc2obj/j-mc-2-obj/blob/78db8562141f41df6ad2260cde31fd1c8389f398/src/org/jmc/Chunk.java#L292-L294
