### ISSUE TITLE
Adding support for different dimensions

### ISSUE THREAD

**Issue by rockedsocks** [jmc2obj/j-mc-2-obj#142]
It would be nice if the program was able to render the Nether and End dimensions as well as the Overworld. I think it would help a lot when it comes to creating certain scenes where you need other dimensions.

**Comment by mmdanggg2** [comment]
It works fine with the nether and end, you just change the dimension with the dropdown next to the load button.
You need to lower the ceiling slider to be able to see inside the nether due to the bedrock ceiling.
![image](https://user-images.githubusercontent.com/3161587/101261852-fcd9f600-3731-11eb-94ef-9a3ac73e93cf.png)
The new nether blocks haven't been added yet though.
