### ISSUE TITLE
JMC 113 and 114 grass paths bugged/removed

### ISSUE THREAD

**Issue by xelacreations** [jmc2obj/j-mc-2-obj#173]
Hi,

I recently updated to JMC 114 and noticed that suddenly all the grass paths where gone from exports.
I checked if they where just hidden but no, they where ticked on.

Even after updating the world to 1.17 it still got removed, and when going back to JMC 112 the grass paths are back.
I also tried a clean folder for 114 but then the paths are still gone.

Is there any fix for this?

- Xela

**Comment by mmdanggg2** [comment]
I'm not seeing this issue on 114 with a 1.17 world, maybe try to restore factory settings. Are there any errors/messages in the console/log?
![image](https://user-images.githubusercontent.com/3161587/139961354-98d8031c-4eff-4675-a721-1474214c6c89.png)

**Comment by xelacreations** [comment]
Hey,

So after some invesigations new world in 1.17.1 work with paths exporting.
But when I grab a world with 1.16 or older they start not exporting anymore even after opening the world in 1.17 afterwards.

I don't see any errors in the console and it says it exports right but they just do not appear and it just removes them.

- Xela

**Comment by mmdanggg2** [comment]
Ok, I had another look and this is because `grass_path` was renamed to `dirt_path` in 1.17 and so it can't find the block model for `grass_path` from the 1.16 world in the 1.17 minecraft jar. It should say in the log that it couldn't find the block in the resource packs when you export:
![image](https://user-images.githubusercontent.com/3161587/140233477-2a1846d6-4fd4-4726-8f27-d7ecf0f797f6.png)
I'll have a look at making that error more visible.

I found that loading the chunks in 1.17 did update the block to `dirt_path` and that exported fine afterwards. It could be that just opening the world and not being near those chunks doesn't update them.
If you want to keep using 1.16 then you can manually set 1.16 as the resource pack to use:
![image](https://user-images.githubusercontent.com/3161587/140233177-0517bbe7-65e2-4460-aabd-f575a1d0e7fa.png)
