### ISSUE TITLE
Export issue

### ISSUE THREAD

**Issue by michal212345** [jmc2obj/j-mc-2-obj#183]
"Create a separate object for each chunk" will stop "Create a separate object for each material" from working
It will only export the mesh for Each chunk and ignore material
It seems as if the exporter will prioritise the lowest option

Export settings:
![image](https://user-images.githubusercontent.com/20019071/159295561-ee97e2c8-afbc-43f3-8fad-bbadec03475d.png)

Exported mesh:
![image](https://user-images.githubusercontent.com/20019071/159295395-085925af-7237-4129-9451-70ddc0cbfa57.png)

**Comment by mmdanggg2** [comment]
This was previously working but ended up getting disabled in another fix because maya doesn't like objs where an object is defined in multiple places. This fix just reenables that for when they're both on, I think it should be fine since the original problem was caused by the chunk objects being split by material so with the material name on the objects it won't have that issue of the same object being defined multiple times.

https://www.mediafire.com/file/3clhvf57iqbfejx/jMc2Obj-117-test1.jar/file
See how it goes, I'll probably release a new version with this fix soon.

**Comment by michal212345** [comment]
That works perfectly well on my Maya! Any chance you can add a feature for occluded single blocks?

**Comment by mmdanggg2** [comment]
I will have a quick look and see if that's easy to do. Seems like quite a niche use case so no promises.

**Comment by mmdanggg2** [comment]
Ok, that was a simple change. Hopefully made the options a little clearer too: https://www.mediafire.com/file/h6k2yrv464997p4/jMc2Obj-117-test2.jar/file

**Comment by michal212345** [comment]
Works perfectly and the UI works a lot better now IMO, Thank you!
