### ISSUE TITLE
IllegalArgumentException when exporting textures

### ISSUE THREAD

**Issue by NJDaeger** [jmc2obj/j-mc-2-obj#186]
Hi, we are working on trying to export our map with our resourcepack, however, when it comes to exporting textures, we are running into an error.

![image](https://user-images.githubusercontent.com/18237863/161839591-9a64eba9-b348-49dd-b4d8-cf0f7bfb50b6.png)

Is there something wrong with the resource pack in this case? Or is there anther issue at play? Is there some kind of verbose logging we can enable to see what texture is causing this problem?

Thanks!

**Comment by mmdanggg2** [comment]
hmm, that seems to indicate one of your textures does not conform to any of the java image formats. Could you send me the resource pack and I can have a closer look.

**Comment by NJDaeger** [comment]
Can do; http://textures.greenfieldmc.net

As the lead on that resourcepack, I can think of a single texture that might be out of the ordinary for a resourcepack- would be the red candle off texture and red candle texture. Those are 17x17 pixels, however, they seem to work in game.

Thanks for looking into it!

**Comment by mmdanggg2** [comment]
It is the lapis_block.png has been saved as a 16-bit png rather than the usual 8-bit. I've written a fix so it can deal with that now.
That was only an issue with the 1.16 version from your website. However I first downloaded the 1.17 version from the github link and that has a few problems with it that jmc was tripping up on:
[blockstates/nether_wart.json](https://github.com/GreenfieldMC/Greenfield-Texturepack/blob/b68bbc5e1cf7ab28554a7ca7144231d39ac690b8/assets/minecraft/blockstates/nether_wart.json#L26) has an errornous extra brace
[tex/block/powered_rail_on.png.mcmeta](https://github.com/GreenfieldMC/Greenfield-Texturepack/blob/b68bbc5e1cf7ab28554a7ca7144231d39ac690b8/assets/minecraft/textures/block/powered_rail_on.png.mcmeta#L4) has an invalid frametime, it has to be an integer, not float
[models/block/green_candle_base.json](https://github.com/GreenfieldMC/Greenfield-Texturepack/blob/b68bbc5e1cf7ab28554a7ca7144231d39ac690b8/assets/minecraft/models/block/green_candle_base.json#L5) has an invalid texture defined

Thanks for reporting, jmc should be able to deal with these errors a bit better now.

**Comment by NJDaeger** [comment]
Thank you for showing us those. I'm not sure how I missed those when it came to evaluating the resourcepack for production use.

I will fix those, glad we could help each other out :) 

Appreciate it!
