### ISSUE TITLE
Add 1.12.2 option to allow for mods (enhancement) 

### ISSUE THREAD

**Issue by TheCatin** [jmc2obj/j-mc-2-obj#189]
adding modded blocks is so easy on 117, however, 1.12.2 is not supported and you'll have to downgrade to a version without mods to export. Is it possible to somehow conbine the option for modded blocks with an old version- or better yet: add an option for 1.12 chunks  on the new version.

**Comment by mmdanggg2** [comment]
Unfortunately the reason modded blocks are so easy is because of the changes minecraft made to the world format in 1.13, using the text block ids rather than numbers. 
I did want to try and get loading of old maps working but that poses a lot of chalenges to be able to properly convert from the old ids and data values to the new ids and blockstates. It might be possible to add in the resource pack code to the older version of jmc but that just seems like a waste of time. 
In either case you would have to create a config which means going through each modded block, figure out the block id (which I belive is unique to each modpack) are and what data values map to what blockstates to be able to export them correctly which is not easy.

It is possible to add modded blocks to the old version of jmc but you still need to figure out the block ids and then define a model for it either using one of existing models (Cube etc.), creating obj models of the block and using the Mesh model or writing your own model code in java.
