### ISSUE TITLE
Blender new obj importer won't split mesh

### ISSUE THREAD

**Issue by hd926** [jmc2obj/j-mc-2-obj#195]
First of all i'm not sure if this is a bug in jmc2obj or blender.

The new c++ importer for blender wont split the imported mesh anymore compared to the old importer. For now i can still use the old importer but they will remove the old one in a future update.

The new importer does split other objs which are not exported from jmc2obj, so i thought it's an issue on jmc2objs end.

**Comment by mmdanggg2** [comment]
So jmc actually does export the obj incorrectly, it puts the separate objects in as (vertex) groups instead of actual obj objects. AFAIK this is because maya imports objs incorrectly, using the obj groups to separate objects. The old blender importer had the option to use groups as objects but the new one doesn't yet. So unless maya has fixed their importer now, I don't think we should update jmc to use objects yet, as much as I would like to. Perhaps we can add an option to switch between it. Best bet is to see if the new importer can get these options back.

**Comment by hd926** [comment]
The problem is, they said that the new importer is feature complete. Thats the reason the old importer will be renamed to legacy. But for now it's not big of a problem.

**Comment by mmdanggg2** [comment]
Addressed with 9898c2270c8c3965f2b797fb8883e2e504916ee0
