### ISSUE TITLE
Support for block modes like FramedBlocks etc 

### ISSUE THREAD

**Issue by TheLifeweaver** [jmc2obj/j-mc-2-obj#229]
I know its unlikely but I wanted to ask if you'd consider adding support for mods like FramedBlocks that provide a lot of extra customizability. I'm not entirely sure if this would be in scope but I thought I'd ask.

**Comment by mmdanggg2** [comment]
It would be nice to have obviously. The problem is many of those mods generate the models with code at run time so you'd have to try and replicate however that works in JMC. Even if the mod is open source, that's not easy to do, and then it'd only work for that one mod anyway. Do that for one mod and people will start asking for others etc. which is a headache I don't wanna deal with either.

If the mods use the regular minecraft resource pack models though, they should work already, you just need to add the mod jar as a resource pack in the settings. But that's down to if the mod creator decided to go with that method for their mod or not.
